import asyncio
import math
import random
import hashlib
from typing import AsyncGenerator, List, Optional

from app.services.llm_engine import LLMEngine
from app.schemas.openai import ChatMessage
from app.core.config import settings


# ─── Dummy response templates ─────────────────────────────────────────────────

CHAT_RESPONSES = [
    "I'm a simulated LLM response from LLM Serve. Your messages have been received and processed. "
    "In a real deployment, this would be replaced by an actual model's output.",

    "Thank you for your message! This is a dummy response from the LLM Serve inference engine. "
    "The system is operating correctly — token verification passed, routing worked, and the request pipeline is functional.",

    "Hello! I'm running in dummy mode. Your request was successfully authenticated and routed. "
    "The actual model inference is stubbed out, but all middleware, schemas, and API compatibility layers are live.",

    "Interesting question! While I can't provide a real answer in dummy mode, I can confirm that "
    "your request hit the correct endpoint, passed authentication, and was processed by the inference pipeline.",

    "This response is generated by the DummyInferenceEngine. In production you'd swap this with a "
    "real backend (vLLM, HuggingFace, OpenAI proxy, etc.). Everything else — auth, rate limiting, streaming, "
    "schema validation — is fully functional.",
]

SYSTEM_AWARE_RESPONSES = {
    "you are a helpful assistant": "I'm a helpful assistant running in LLM Serve dummy mode. How can I help you today?",
    "you are a pirate": "Arrr! Ahoy there! This be a dummy response from LLM Serve, but I'm playing my pirate role as instructed!",
    "you are a poet": "In lines of code and silicon dreams, / A dummy model softly streams. / LLM Serve stands proud and tall, / Ready to serve your requests, one and all.",
    "you are an expert": "As an expert (in dummy mode), I can confirm that your LLM Serve setup is configured correctly.",
}

KEYWORD_RESPONSES = {
    "hello": "Hello! This is LLM Serve responding in dummy mode.",
    "hi": "Hi there! Dummy response from LLM Serve.",
    "what is": "That's a great question. In dummy mode, I can't give you a real answer, but LLM Serve received your request successfully.",
    "how do": "Here's how: In a real deployment, I'd provide detailed instructions. But in dummy mode, I'm just confirming your request was received and processed correctly.",
    "explain": "Explanation (dummy mode): Your request was properly authenticated, rate-limited, and routed through the LLM Serve pipeline.",
    "write": "Here's what I'd write (dummy mode): [Generated content would appear here once connected to a real model backend].",
    "summarize": "Summary (dummy mode): Your text was received. In production, a real model would summarize it here.",
    "translate": "Translation (dummy mode): Your text was received. Connect a real translation model to get actual output.",
}


def _pick_response(messages: List[ChatMessage]) -> str:
    """Pick a contextually aware dummy response based on the messages."""
    # Check system message
    for msg in messages:
        if msg.role.value == "system" and msg.content:
            content_lower = msg.content.lower()
            for key, response in SYSTEM_AWARE_RESPONSES.items():
                if key in content_lower:
                    return response

    # Check last user message for keywords
    for msg in reversed(messages):
        if msg.role.value == "user" and msg.content:
            content_lower = msg.content.lower()
            for keyword, response in KEYWORD_RESPONSES.items():
                if keyword in content_lower:
                    return response

    # Fall back to random response
    return random.choice(CHAT_RESPONSES)


def _count_tokens_simple(text: str) -> int:
    """Rough token estimation: ~4 chars per token."""
    return max(1, len(text) // 4)


def _generate_embedding(text: str, dimensions: int = 1536) -> List[float]:
    """Generate a deterministic fake embedding vector based on text hash."""
    seed = int(hashlib.md5(text.encode()).hexdigest(), 16) % (2**32)
    rng = random.Random(seed)
    vec = [rng.gauss(0, 1) for _ in range(dimensions)]
    # L2-normalize
    norm = math.sqrt(sum(x * x for x in vec))
    if norm > 0:
        vec = [x / norm for x in vec]
    return vec


MODEL_EMBEDDING_DIMS = {
    "text-embedding-ada-002": 1536,
    "text-embedding-3-small": 1536,
    "text-embedding-3-large": 3072,
}


class DummyInferenceEngine(LLMEngine):
    """
    A fully functional dummy inference engine that simulates LLM responses.
    Replace with a real backend (vLLM, HuggingFace Transformers, Ollama, etc.)
    by implementing the LLMEngine interface.
    """

    async def chat(
        self,
        messages: List[ChatMessage],
        model: str,
        temperature: float = 1.0,
        top_p: float = 1.0,
        max_tokens: Optional[int] = None,
        stop: Optional[List[str]] = None,
        **kwargs,
    ) -> str:
        await asyncio.sleep(settings.DUMMY_LATENCY_MS / 1000)
        response = _pick_response(messages)
        if max_tokens:
            # Truncate to approximate token limit
            words = response.split()
            approx_words = min(len(words), max_tokens // 2)
            response = " ".join(words[:approx_words])
        return response

    async def stream_chat(
        self,
        messages: List[ChatMessage],
        model: str,
        temperature: float = 1.0,
        top_p: float = 1.0,
        max_tokens: Optional[int] = None,
        stop: Optional[List[str]] = None,
        **kwargs,
    ) -> AsyncGenerator[str, None]:
        await asyncio.sleep(settings.DUMMY_LATENCY_MS / 1000)
        full_response = _pick_response(messages)
        if max_tokens:
            words = full_response.split()
            approx_words = min(len(words), max_tokens // 2)
            full_response = " ".join(words[:approx_words])

        # Stream word by word with small delays
        words = full_response.split(" ")
        for i, word in enumerate(words):
            chunk = word if i == len(words) - 1 else word + " "
            yield chunk
            await asyncio.sleep(settings.STREAM_CHUNK_DELAY_MS / 1000)

    async def complete(
        self,
        prompt: str,
        model: str,
        temperature: float = 1.0,
        top_p: float = 1.0,
        max_tokens: int = 16,
        stop: Optional[List[str]] = None,
        **kwargs,
    ) -> str:
        await asyncio.sleep(settings.DUMMY_LATENCY_MS / 1000)
        completions = [
            " The quick brown fox jumps over the lazy dog.",
            " In a world where AI models are served via APIs,",
            " Once upon a time, a developer deployed LLM Serve and",
            " The answer to your question lies in the implementation details of",
            " According to recent research, language models are capable of",
        ]
        # Deterministically pick based on prompt hash
        idx = int(hashlib.md5(prompt.encode()).hexdigest(), 16) % len(completions)
        result = completions[idx]
        # Respect max_tokens roughly
        words = result.split()
        approx_words = min(len(words), max_tokens // 2)
        return " ".join(words[:approx_words])

    async def embed(
        self,
        texts: List[str],
        model: str,
        **kwargs,
    ) -> List[List[float]]:
        await asyncio.sleep(settings.DUMMY_LATENCY_MS / 1000)
        dims = MODEL_EMBEDDING_DIMS.get(model, 1536)
        return [_generate_embedding(text, dims) for text in texts]

    def count_tokens(self, text: str, model: str) -> int:
        return _count_tokens_simple(text)


# Singleton engine instance
dummy_engine = DummyInferenceEngine()

_local_engine: Optional[LLMEngine] = None

def get_engine() -> LLMEngine:
    if settings.DUMMY_MODE:
        return dummy_engine
    if _local_engine is None:
        raise RuntimeError("Local engine not initialized. Ensure startup hook ran.")
    return _local_engine

def set_local_engine(engine: LLMEngine):
    global _local_engine
    _local_engine = engine
